#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

hours=0

while [ $hours -le 12 ]
do

	minute=1

	echo "Hour: $hours"
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hours++))
done
